name: Run Trading Bot

on:
  schedule:
    # Runs every 5 minutes — change as needed
    - cron: "*/5 * * * *"
  workflow_dispatch: # allows manual trigger

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # choose your Python version

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot script
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
        run: python bot.py
